[rb] Remove `prism` dependency (#16437)
* [rb] Remove `prism` dependency

This project does not use prism at all. At most it is being used by rubocop during local development.

It was added in https://github.com/SeleniumHQ/selenium/pull/16357 but it is unclear to me why.
I just bumped it for this repo, perhaps that JRuby issue has since been fixed.
Either way, it should not be part of the gemspec.

* Pin prism to 1.4.0 for the project

It fails to build with the following error:
src/prism.c: In function ‘context_terminator’:
src/prism.c:8651:62: error: conversion to ‘unsigned int’ from ‘int’ may change
the sign of the result [-Werror=sign-conversion]
8651 |     return token->type < 32 && (context_terminators[context] & (1 <<
token->type));
      |                                                              ^
cc1: all warnings being treated as errors

---------

Co-authored-by: Diego Molina <diemol@users.noreply.github.com>